  apiVersion: apps/v1
  kind: Deployment

  metadata:
    name: backend-deployment
    namespace: chat-app

  spec:
    replicas: 1
    selector:
      matchLabels:
        app: backend

    template:
      metadata:
        name: backend-pod
        namespace: chat-app
        labels:
          app: backend

      spec:
        containers:
        - name: chat-app-backend
          image: reyrox2005/backend-image
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              value: production
            - name: PORT 
              value: "5001"
            - name: MONGODB_URI
              value: "mongodb://root:root@mongodb-service:27017/?authSource=admin"
            - name: JWT_SECRET
              value: "my-secretkey"